### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by tvladyslav** [ajmwagar/lori#2]
Platform - Raspberry PI 4
Kernel - Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux
Rust - rustc 1.54.0 (a178d0322 2021-07-26)

Any traffic type leads to segmentation fault.

```
pi@raspberrypi:~/sources/lor-axe/target/debug $ RUST_BACKTRACE=full ./loraxe google.com -f
 2022-02-25 17:48:29 INFO  loraxe > Starting UDP Flood on google.com
Sending packet
thread '<unnamed>' panicked at 'attempted to leave type `nodrop::NoDrop<(epoch::Epoch, garbage::Bag)>` uninitialized, which is invalid', /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/mem/mod.rs:660:9
stack backtrace:
   0:   0x7b602c - std::backtrace_rs::backtrace::libunwind::trace::h271512b7e50a40f9
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:   0x7b602c - std::backtrace_rs::backtrace::trace_unsynchronized::h0de36f9f48a9789a
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:   0x7b602c - std::sys_common::backtrace::_print_fmt::h9c998b5818c3a976
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:   0x7b602c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e66bfce45c13f11
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:   0x7d4648 - core::fmt::write::hcbd55b5acee631c7
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:   0x7b1698 - std::io::Write::write_fmt::h2be04b6e1e4c8262
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:   0x7b84b4 - std::sys_common::backtrace::_print::h4000d09a64caf417
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:   0x7b84b4 - std::sys_common::backtrace::print::h9397e356af614514
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:   0x7b84b4 - std::panicking::default_hook::{{closure}}::h54f6cd7ea48c553e
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:   0x7b7e9c - std::panicking::default_hook::h4aabf4e2b8a8ec93
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:   0x7b8ba0 - std::panicking::rust_panic_with_hook::ha699e70e3eeda698
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:   0x7b8640 - std::panicking::begin_panic_handler::{{closure}}::h5986d26c62ba06f9
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:517:13
  12:   0x7b65e4 - std::sys_common::backtrace::__rust_end_short_backtrace::h8c9f2f7ff814f051
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:   0x7b85c0 - rust_begin_unwind
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:   0x4c7890 - core::panicking::panic_fmt::h25d1c2df73602ae3
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
  15:   0x4c77ec - core::panicking::panic::he1753c57c14ebf62
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:50:5
  16:   0x5434c0 - core::mem::uninitialized::h705fc486b7aab03c
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/mem/mod.rs:660:9
  17:   0x5434c0 - crossbeam_epoch::sync::queue::Queue<T>::new::hb1c9df21da9a33d8
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/crossbeam-epoch-0.3.1/src/sync/queue.rs:57:28
  18:   0x54182c - crossbeam_epoch::internal::Global::new::h6c7c9ebb71a698ab
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/crossbeam-epoch-0.3.1/src/internal.rs:63:20
  19:   0x53c23c - crossbeam_epoch::collector::Collector::new::h309484e960f4432f
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/crossbeam-epoch-0.3.1/src/collector.rs:32:38
  20:   0x53f6c8 - <crossbeam_epoch::default::COLLECTOR as core::ops::deref::Deref>::deref::__static_ref_initialize::h490c3b4ef331aa10
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/crossbeam-epoch-0.3.1/src/default.rs:12:39
  21:   0x53f6c8 - core::ops::function::FnOnce::call_once::hb752d341d23ca140
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  22:   0x545f28 - lazy_static::lazy::Lazy<T>::get::{{closure}}::hb371c3603f8c5a71
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/lazy_static-1.3.0/src/inline_lazy.rs:28:29
  23:   0x53e2e0 - std::sync::once::Once::call_once::{{closure}}::hfbfcdfa0bec8d397
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sync/once.rs:261:41
  24:   0x4c6d38 - std::sync::once::Once::call_inner::h48547a57e41ea957
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sync/once.rs:418:21
  25:   0x53e268 - std::sync::once::Once::call_once::h670b2fcc0e514c38
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sync/once.rs:261:9
  26:   0x546d0c - lazy_static::lazy::Lazy<T>::get::hdc514b299cb840f1
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/lazy_static-1.3.0/src/inline_lazy.rs:27:9
  27:   0x546d0c - <crossbeam_epoch::default::COLLECTOR as core::ops::deref::Deref>::deref::__stability::h3475e404f127d713
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/lazy_static-1.3.0/src/lib.rs:138:21
  28:   0x546d0c - <crossbeam_epoch::default::COLLECTOR as core::ops::deref::Deref>::deref::h099c86202ddf102e
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/lazy_static-1.3.0/src/lib.rs:140:17
  29:   0x546d94 - crossbeam_epoch::default::HANDLE::__init::h17a4cb36d0be3a79
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/crossbeam-epoch-0.3.1/src/default.rs:17:29
  30:   0x53f65c - core::ops::function::FnOnce::call_once::h13844241bfa8f577
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  31:   0x53f008 - std::thread::local::lazy::LazyKeyInner<T>::initialize::hfecad9606981b1a9
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:432:25
  32:   0x53e3c0 - std::thread::local::fast::Key<T>::try_initialize::hb4997cff2954fda3
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:610:31
  33:   0x53e540 - std::thread::local::fast::Key<T>::get::hc3c1b7611392a772
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:593:29
  34:   0x5292fc - crossbeam_epoch::default::HANDLE::__getit::h69605d73ac7bedcf
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:311:26
  35:   0x52e6ac - std::thread::local::LocalKey<T>::try_with::hbee420fad9b0687f
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:399:32
  36:   0x52e35c - std::thread::local::LocalKey<T>::with::h90034f6c91c77397
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:376:9
  37:   0x529328 - crossbeam_epoch::default::is_pinned::h220444b67d17cc92
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/crossbeam-epoch-0.3.1/src/default.rs:33:5
  38:   0x52e000 - crossbeam_deque::Stealer<T>::steal::h2dd767f7b4cb1b9d
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/crossbeam-deque-0.2.0/src/lib.rs:714:12
  39:   0x51dd2c - rayon_core::registry::WorkerThread::steal::{{closure}}::h1b8cce471ac01958
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/rayon-core-1.4.1/src/registry.rs:614:27
  40:   0x51bad8 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::he2c0bfee21168c52
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:269:13
  41:   0x53456c - core::iter::traits::iterator::Iterator::find_map::check::{{closure}}::ha04a682f307257b3
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:2350:32
  42:   0x51fe74 - core::iter::adapters::filter::filter_try_fold::{{closure}}::h0d0cef9b5cecc340
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/filter.rs:44:44
  43:   0x51f5f4 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h95e1440e881ecb45
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:269:13
  44:   0x5347b0 - core::iter::traits::iterator::Iterator::try_fold::h018a144b6c4eee2b
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:1972:21
  45:   0x530d60 - <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold::h641ccbadc2250afb
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/chain.rs:104:19
  46:   0x51eda4 - <core::iter::adapters::filter::Filter<I,P> as core::iter::traits::iterator::Iterator>::try_fold::h113601509bdb9308
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/filter.rs:93:9
  47:   0x51f6fc - core::iter::traits::iterator::Iterator::find_map::ha8cc1c930166e50b
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/traits/iterator.rs:2356:9
  48:   0x533660 - <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next::hc049be7cfcbb9714
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/iter/adapters/filter_map.rs:61:9
  49:   0x51dc74 - rayon_core::registry::WorkerThread::steal::hd5c1d577a75a21db
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/rayon-core-1.4.1/src/registry.rs:608:9
  50:   0x51da24 - rayon_core::registry::WorkerThread::wait_until_cold::{{closure}}::hfcf9de1bf8b8b104
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/rayon-core-1.4.1/src/registry.rs:565:48
  51:   0x52715c - core::option::Option<T>::or_else::hc93b17b765d2f722
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/option.rs:790:21
  52:   0x51d480 - rayon_core::registry::WorkerThread::wait_until_cold::h29406b410d246a33
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/rayon-core-1.4.1/src/registry.rs:564:32
  53:   0x51d2a4 - rayon_core::registry::WorkerThread::wait_until::h3d8e370070cc70fb
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/rayon-core-1.4.1/src/registry.rs:544:13
  54:   0x51e17c - rayon_core::registry::main_loop::h42e8e94fa10b7d1a
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/rayon-core-1.4.1/src/registry.rs:666:5
  55:   0x51c914 - rayon_core::registry::Registry::new::{{closure}}::h98d72f96a2c84eeb
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/rayon-core-1.4.1/src/registry.rs:135:54
  56:   0x51a3f0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6667071f52dabbf0
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:125:18
  57:   0x52f0e8 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hfc151a088c570d00
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:481:17
  58:   0x51e8ec - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h3e37d574727f3b3c
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347:9
  59:   0x524cd4 - std::panicking::try::do_call::hbfd47a31aff98764
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  60:   0x525df8 - __rust_try
  61:   0x524b8c - std::panicking::try::h93436d6213e91854
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  62:   0x51f4e0 - std::panic::catch_unwind::h96ed261593188849
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  63:   0x52ef48 - std::thread::Builder::spawn_unchecked::{{closure}}::haa6e6e87c508f2a7
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:480:30
  64:   0x531554 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h616943cb462bbb39
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  65:   0x7bbc3c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he96cb9b6900837c8
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
  66:   0x7bbc3c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6480d459fa5aed6d
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
  67:   0x7bbc3c - std::sys::unix::thread::Thread::new::thread_start::hd80c0348cf798ed3
                       at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys/unix/thread.rs:71:17
Segmentation fault

```

**Comment by tvladyslav** [comment]
Please bump "rayon" version to 1.5.1 and it is going to work.
